// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recyclingsupport.proto

package recyclingsupport;

public interface ChatMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:recyclingsupport.ChatMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Nombre del remitente (por ejemplo, "client" o "SupportAgent")
   * </pre>
   *
   * <code>string sender = 1;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <pre>
   * Nombre del remitente (por ejemplo, "client" o "SupportAgent")
   * </pre>
   *
   * <code>string sender = 1;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <pre>
   * Contenido del mensaje
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Contenido del mensaje
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Marca de tiempo del mensaje en formato ISO (por ejemplo, "2025-08-01T12:00:00Z")
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <pre>
   * Marca de tiempo del mensaje en formato ISO (por ejemplo, "2025-08-01T12:00:00Z")
   * </pre>
   *
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();
}
