// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: recyclingsupport.proto

package recyclingsupport;

public final class Recyclingsupport {
  private Recyclingsupport() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_recyclingsupport_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_recyclingsupport_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026recyclingsupport.proto\022\020recyclingsuppo" +
      "rt\"A\n\013ChatMessage\022\016\n\006sender\030\001 \001(\t\022\017\n\007mes" +
      "sage\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\t2c\n\027Recycli" +
      "ngSupportService\022H\n\004Chat\022\035.recyclingsupp" +
      "ort.ChatMessage\032\035.recyclingsupport.ChatM" +
      "essage(\0010\001B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_recyclingsupport_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_recyclingsupport_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_recyclingsupport_ChatMessage_descriptor,
        new java.lang.String[] { "Sender", "Message", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
