// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase.proto

package conepurchase;

public interface ConeSaleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conepurchase.ConeSaleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 quantity = 1;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <pre>
   * Client zone
   * </pre>
   *
   * <code>string location = 2;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <pre>
   * Client zone
   * </pre>
   *
   * <code>string location = 2;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
