// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase.proto

package conepurchase;

/**
 * Protobuf type {@code conepurchase.ConeSaleResponse}
 */
public final class ConeSaleResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:conepurchase.ConeSaleResponse)
    ConeSaleResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ConeSaleResponse.newBuilder() to construct.
  private ConeSaleResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ConeSaleResponse() {
    messageType_ = "";
    message_ = "";
    day_ = "";
    timeslot_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ConeSaleResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ConeSaleResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            messageType_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            day_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            timeslot_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return conepurchase.Purchase.internal_static_conepurchase_ConeSaleResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return conepurchase.Purchase.internal_static_conepurchase_ConeSaleResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            conepurchase.ConeSaleResponse.class, conepurchase.ConeSaleResponse.Builder.class);
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object messageType_;
  /**
   * <pre>
   * "price", "logisticStatus", "pickupOption", "note"
   * </pre>
   *
   * <code>string messageType = 1;</code>
   * @return The messageType.
   */
  @java.lang.Override
  public java.lang.String getMessageType() {
    java.lang.Object ref = messageType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      messageType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "price", "logisticStatus", "pickupOption", "note"
   * </pre>
   *
   * <code>string messageType = 1;</code>
   * @return The bytes for messageType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageTypeBytes() {
    java.lang.Object ref = messageType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      messageType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <pre>
   * Value depends on messageType
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Value depends on messageType
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DAY_FIELD_NUMBER = 3;
  private volatile java.lang.Object day_;
  /**
   * <pre>
   * Optional: only present when messageType is "pickupOption"
   * </pre>
   *
   * <code>string day = 3;</code>
   * @return The day.
   */
  @java.lang.Override
  public java.lang.String getDay() {
    java.lang.Object ref = day_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      day_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional: only present when messageType is "pickupOption"
   * </pre>
   *
   * <code>string day = 3;</code>
   * @return The bytes for day.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDayBytes() {
    java.lang.Object ref = day_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      day_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESLOT_FIELD_NUMBER = 4;
  private volatile java.lang.Object timeslot_;
  /**
   * <pre>
   * Optional: for pickup option
   * </pre>
   *
   * <code>string timeslot = 4;</code>
   * @return The timeslot.
   */
  @java.lang.Override
  public java.lang.String getTimeslot() {
    java.lang.Object ref = timeslot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timeslot_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional: for pickup option
   * </pre>
   *
   * <code>string timeslot = 4;</code>
   * @return The bytes for timeslot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimeslotBytes() {
    java.lang.Object ref = timeslot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timeslot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messageType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(day_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, day_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeslot_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, timeslot_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(messageType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, messageType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(day_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, day_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timeslot_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, timeslot_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof conepurchase.ConeSaleResponse)) {
      return super.equals(obj);
    }
    conepurchase.ConeSaleResponse other = (conepurchase.ConeSaleResponse) obj;

    if (!getMessageType()
        .equals(other.getMessageType())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getDay()
        .equals(other.getDay())) return false;
    if (!getTimeslot()
        .equals(other.getTimeslot())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMessageType().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + DAY_FIELD_NUMBER;
    hash = (53 * hash) + getDay().hashCode();
    hash = (37 * hash) + TIMESLOT_FIELD_NUMBER;
    hash = (53 * hash) + getTimeslot().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static conepurchase.ConeSaleResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static conepurchase.ConeSaleResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static conepurchase.ConeSaleResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static conepurchase.ConeSaleResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static conepurchase.ConeSaleResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static conepurchase.ConeSaleResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static conepurchase.ConeSaleResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static conepurchase.ConeSaleResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static conepurchase.ConeSaleResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static conepurchase.ConeSaleResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static conepurchase.ConeSaleResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static conepurchase.ConeSaleResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(conepurchase.ConeSaleResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code conepurchase.ConeSaleResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:conepurchase.ConeSaleResponse)
      conepurchase.ConeSaleResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return conepurchase.Purchase.internal_static_conepurchase_ConeSaleResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return conepurchase.Purchase.internal_static_conepurchase_ConeSaleResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              conepurchase.ConeSaleResponse.class, conepurchase.ConeSaleResponse.Builder.class);
    }

    // Construct using conepurchase.ConeSaleResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageType_ = "";

      message_ = "";

      day_ = "";

      timeslot_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return conepurchase.Purchase.internal_static_conepurchase_ConeSaleResponse_descriptor;
    }

    @java.lang.Override
    public conepurchase.ConeSaleResponse getDefaultInstanceForType() {
      return conepurchase.ConeSaleResponse.getDefaultInstance();
    }

    @java.lang.Override
    public conepurchase.ConeSaleResponse build() {
      conepurchase.ConeSaleResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public conepurchase.ConeSaleResponse buildPartial() {
      conepurchase.ConeSaleResponse result = new conepurchase.ConeSaleResponse(this);
      result.messageType_ = messageType_;
      result.message_ = message_;
      result.day_ = day_;
      result.timeslot_ = timeslot_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof conepurchase.ConeSaleResponse) {
        return mergeFrom((conepurchase.ConeSaleResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(conepurchase.ConeSaleResponse other) {
      if (other == conepurchase.ConeSaleResponse.getDefaultInstance()) return this;
      if (!other.getMessageType().isEmpty()) {
        messageType_ = other.messageType_;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getDay().isEmpty()) {
        day_ = other.day_;
        onChanged();
      }
      if (!other.getTimeslot().isEmpty()) {
        timeslot_ = other.timeslot_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      conepurchase.ConeSaleResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (conepurchase.ConeSaleResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object messageType_ = "";
    /**
     * <pre>
     * "price", "logisticStatus", "pickupOption", "note"
     * </pre>
     *
     * <code>string messageType = 1;</code>
     * @return The messageType.
     */
    public java.lang.String getMessageType() {
      java.lang.Object ref = messageType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "price", "logisticStatus", "pickupOption", "note"
     * </pre>
     *
     * <code>string messageType = 1;</code>
     * @return The bytes for messageType.
     */
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "price", "logisticStatus", "pickupOption", "note"
     * </pre>
     *
     * <code>string messageType = 1;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "price", "logisticStatus", "pickupOption", "note"
     * </pre>
     *
     * <code>string messageType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      
      messageType_ = getDefaultInstance().getMessageType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "price", "logisticStatus", "pickupOption", "note"
     * </pre>
     *
     * <code>string messageType = 1;</code>
     * @param value The bytes for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      messageType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * Value depends on messageType
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Value depends on messageType
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Value depends on messageType
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Value depends on messageType
     * </pre>
     *
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Value depends on messageType
     * </pre>
     *
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object day_ = "";
    /**
     * <pre>
     * Optional: only present when messageType is "pickupOption"
     * </pre>
     *
     * <code>string day = 3;</code>
     * @return The day.
     */
    public java.lang.String getDay() {
      java.lang.Object ref = day_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        day_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional: only present when messageType is "pickupOption"
     * </pre>
     *
     * <code>string day = 3;</code>
     * @return The bytes for day.
     */
    public com.google.protobuf.ByteString
        getDayBytes() {
      java.lang.Object ref = day_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        day_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional: only present when messageType is "pickupOption"
     * </pre>
     *
     * <code>string day = 3;</code>
     * @param value The day to set.
     * @return This builder for chaining.
     */
    public Builder setDay(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      day_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional: only present when messageType is "pickupOption"
     * </pre>
     *
     * <code>string day = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDay() {
      
      day_ = getDefaultInstance().getDay();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional: only present when messageType is "pickupOption"
     * </pre>
     *
     * <code>string day = 3;</code>
     * @param value The bytes for day to set.
     * @return This builder for chaining.
     */
    public Builder setDayBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      day_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object timeslot_ = "";
    /**
     * <pre>
     * Optional: for pickup option
     * </pre>
     *
     * <code>string timeslot = 4;</code>
     * @return The timeslot.
     */
    public java.lang.String getTimeslot() {
      java.lang.Object ref = timeslot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timeslot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional: for pickup option
     * </pre>
     *
     * <code>string timeslot = 4;</code>
     * @return The bytes for timeslot.
     */
    public com.google.protobuf.ByteString
        getTimeslotBytes() {
      java.lang.Object ref = timeslot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timeslot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional: for pickup option
     * </pre>
     *
     * <code>string timeslot = 4;</code>
     * @param value The timeslot to set.
     * @return This builder for chaining.
     */
    public Builder setTimeslot(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timeslot_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional: for pickup option
     * </pre>
     *
     * <code>string timeslot = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeslot() {
      
      timeslot_ = getDefaultInstance().getTimeslot();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional: for pickup option
     * </pre>
     *
     * <code>string timeslot = 4;</code>
     * @param value The bytes for timeslot to set.
     * @return This builder for chaining.
     */
    public Builder setTimeslotBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timeslot_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:conepurchase.ConeSaleResponse)
  }

  // @@protoc_insertion_point(class_scope:conepurchase.ConeSaleResponse)
  private static final conepurchase.ConeSaleResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new conepurchase.ConeSaleResponse();
  }

  public static conepurchase.ConeSaleResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ConeSaleResponse>
      PARSER = new com.google.protobuf.AbstractParser<ConeSaleResponse>() {
    @java.lang.Override
    public ConeSaleResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ConeSaleResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ConeSaleResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ConeSaleResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public conepurchase.ConeSaleResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

