// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: purchase.proto

package conepurchase;

public interface ConeSaleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:conepurchase.ConeSaleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "price", "logisticStatus", "pickupOption", "note"
   * </pre>
   *
   * <code>string messageType = 1;</code>
   * @return The messageType.
   */
  java.lang.String getMessageType();
  /**
   * <pre>
   * "price", "logisticStatus", "pickupOption", "note"
   * </pre>
   *
   * <code>string messageType = 1;</code>
   * @return The bytes for messageType.
   */
  com.google.protobuf.ByteString
      getMessageTypeBytes();

  /**
   * <pre>
   * Value depends on messageType
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Value depends on messageType
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Optional: only present when messageType is "pickupOption"
   * </pre>
   *
   * <code>string day = 3;</code>
   * @return The day.
   */
  java.lang.String getDay();
  /**
   * <pre>
   * Optional: only present when messageType is "pickupOption"
   * </pre>
   *
   * <code>string day = 3;</code>
   * @return The bytes for day.
   */
  com.google.protobuf.ByteString
      getDayBytes();

  /**
   * <pre>
   * Optional: for pickup option
   * </pre>
   *
   * <code>string timeslot = 4;</code>
   * @return The timeslot.
   */
  java.lang.String getTimeslot();
  /**
   * <pre>
   * Optional: for pickup option
   * </pre>
   *
   * <code>string timeslot = 4;</code>
   * @return The bytes for timeslot.
   */
  com.google.protobuf.ByteString
      getTimeslotBytes();
}
