// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasteanalytics.proto

package wasteanalytics;

public interface DailyReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wasteanalytics.DailyReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
   * @return Whether the dailySummary field is set.
   */
  boolean hasDailySummary();
  /**
   * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
   * @return The dailySummary.
   */
  wasteanalytics.DailySummary getDailySummary();
  /**
   * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
   */
  wasteanalytics.DailySummaryOrBuilder getDailySummaryOrBuilder();

  /**
   * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
   * @return Whether the recyclingBenefits field is set.
   */
  boolean hasRecyclingBenefits();
  /**
   * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
   * @return The recyclingBenefits.
   */
  wasteanalytics.RecyclingBenefits getRecyclingBenefits();
  /**
   * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
   */
  wasteanalytics.RecyclingBenefitsOrBuilder getRecyclingBenefitsOrBuilder();
}
