// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasteanalytics.proto

package wasteanalytics;

public interface DailySummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wasteanalytics.DailySummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 totalWaste = 1;</code>
   * @return The totalWaste.
   */
  int getTotalWaste();

  /**
   * <code>int32 eligibleForSale = 2;</code>
   * @return The eligibleForSale.
   */
  int getEligibleForSale();

  /**
   * <code>int32 recyclable = 3;</code>
   * @return The recyclable.
   */
  int getRecyclable();

  /**
   * <code>int32 nonRecoverable = 4;</code>
   * @return The nonRecoverable.
   */
  int getNonRecoverable();
}
