// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasteanalytics.proto

package wasteanalytics;

/**
 * Protobuf type {@code wasteanalytics.DailySummary}
 */
public final class DailySummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wasteanalytics.DailySummary)
    DailySummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DailySummary.newBuilder() to construct.
  private DailySummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DailySummary() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DailySummary();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DailySummary(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            totalWaste_ = input.readInt32();
            break;
          }
          case 16: {

            eligibleForSale_ = input.readInt32();
            break;
          }
          case 24: {

            recyclable_ = input.readInt32();
            break;
          }
          case 32: {

            nonRecoverable_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailySummary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailySummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            wasteanalytics.DailySummary.class, wasteanalytics.DailySummary.Builder.class);
  }

  public static final int TOTALWASTE_FIELD_NUMBER = 1;
  private int totalWaste_;
  /**
   * <code>int32 totalWaste = 1;</code>
   * @return The totalWaste.
   */
  @java.lang.Override
  public int getTotalWaste() {
    return totalWaste_;
  }

  public static final int ELIGIBLEFORSALE_FIELD_NUMBER = 2;
  private int eligibleForSale_;
  /**
   * <code>int32 eligibleForSale = 2;</code>
   * @return The eligibleForSale.
   */
  @java.lang.Override
  public int getEligibleForSale() {
    return eligibleForSale_;
  }

  public static final int RECYCLABLE_FIELD_NUMBER = 3;
  private int recyclable_;
  /**
   * <code>int32 recyclable = 3;</code>
   * @return The recyclable.
   */
  @java.lang.Override
  public int getRecyclable() {
    return recyclable_;
  }

  public static final int NONRECOVERABLE_FIELD_NUMBER = 4;
  private int nonRecoverable_;
  /**
   * <code>int32 nonRecoverable = 4;</code>
   * @return The nonRecoverable.
   */
  @java.lang.Override
  public int getNonRecoverable() {
    return nonRecoverable_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalWaste_ != 0) {
      output.writeInt32(1, totalWaste_);
    }
    if (eligibleForSale_ != 0) {
      output.writeInt32(2, eligibleForSale_);
    }
    if (recyclable_ != 0) {
      output.writeInt32(3, recyclable_);
    }
    if (nonRecoverable_ != 0) {
      output.writeInt32(4, nonRecoverable_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalWaste_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, totalWaste_);
    }
    if (eligibleForSale_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, eligibleForSale_);
    }
    if (recyclable_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, recyclable_);
    }
    if (nonRecoverable_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, nonRecoverable_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof wasteanalytics.DailySummary)) {
      return super.equals(obj);
    }
    wasteanalytics.DailySummary other = (wasteanalytics.DailySummary) obj;

    if (getTotalWaste()
        != other.getTotalWaste()) return false;
    if (getEligibleForSale()
        != other.getEligibleForSale()) return false;
    if (getRecyclable()
        != other.getRecyclable()) return false;
    if (getNonRecoverable()
        != other.getNonRecoverable()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTALWASTE_FIELD_NUMBER;
    hash = (53 * hash) + getTotalWaste();
    hash = (37 * hash) + ELIGIBLEFORSALE_FIELD_NUMBER;
    hash = (53 * hash) + getEligibleForSale();
    hash = (37 * hash) + RECYCLABLE_FIELD_NUMBER;
    hash = (53 * hash) + getRecyclable();
    hash = (37 * hash) + NONRECOVERABLE_FIELD_NUMBER;
    hash = (53 * hash) + getNonRecoverable();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static wasteanalytics.DailySummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.DailySummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.DailySummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.DailySummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.DailySummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.DailySummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.DailySummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static wasteanalytics.DailySummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static wasteanalytics.DailySummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static wasteanalytics.DailySummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static wasteanalytics.DailySummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static wasteanalytics.DailySummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(wasteanalytics.DailySummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wasteanalytics.DailySummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wasteanalytics.DailySummary)
      wasteanalytics.DailySummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailySummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailySummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wasteanalytics.DailySummary.class, wasteanalytics.DailySummary.Builder.class);
    }

    // Construct using wasteanalytics.DailySummary.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      totalWaste_ = 0;

      eligibleForSale_ = 0;

      recyclable_ = 0;

      nonRecoverable_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailySummary_descriptor;
    }

    @java.lang.Override
    public wasteanalytics.DailySummary getDefaultInstanceForType() {
      return wasteanalytics.DailySummary.getDefaultInstance();
    }

    @java.lang.Override
    public wasteanalytics.DailySummary build() {
      wasteanalytics.DailySummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public wasteanalytics.DailySummary buildPartial() {
      wasteanalytics.DailySummary result = new wasteanalytics.DailySummary(this);
      result.totalWaste_ = totalWaste_;
      result.eligibleForSale_ = eligibleForSale_;
      result.recyclable_ = recyclable_;
      result.nonRecoverable_ = nonRecoverable_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof wasteanalytics.DailySummary) {
        return mergeFrom((wasteanalytics.DailySummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(wasteanalytics.DailySummary other) {
      if (other == wasteanalytics.DailySummary.getDefaultInstance()) return this;
      if (other.getTotalWaste() != 0) {
        setTotalWaste(other.getTotalWaste());
      }
      if (other.getEligibleForSale() != 0) {
        setEligibleForSale(other.getEligibleForSale());
      }
      if (other.getRecyclable() != 0) {
        setRecyclable(other.getRecyclable());
      }
      if (other.getNonRecoverable() != 0) {
        setNonRecoverable(other.getNonRecoverable());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      wasteanalytics.DailySummary parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (wasteanalytics.DailySummary) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int totalWaste_ ;
    /**
     * <code>int32 totalWaste = 1;</code>
     * @return The totalWaste.
     */
    @java.lang.Override
    public int getTotalWaste() {
      return totalWaste_;
    }
    /**
     * <code>int32 totalWaste = 1;</code>
     * @param value The totalWaste to set.
     * @return This builder for chaining.
     */
    public Builder setTotalWaste(int value) {
      
      totalWaste_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 totalWaste = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalWaste() {
      
      totalWaste_ = 0;
      onChanged();
      return this;
    }

    private int eligibleForSale_ ;
    /**
     * <code>int32 eligibleForSale = 2;</code>
     * @return The eligibleForSale.
     */
    @java.lang.Override
    public int getEligibleForSale() {
      return eligibleForSale_;
    }
    /**
     * <code>int32 eligibleForSale = 2;</code>
     * @param value The eligibleForSale to set.
     * @return This builder for chaining.
     */
    public Builder setEligibleForSale(int value) {
      
      eligibleForSale_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 eligibleForSale = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEligibleForSale() {
      
      eligibleForSale_ = 0;
      onChanged();
      return this;
    }

    private int recyclable_ ;
    /**
     * <code>int32 recyclable = 3;</code>
     * @return The recyclable.
     */
    @java.lang.Override
    public int getRecyclable() {
      return recyclable_;
    }
    /**
     * <code>int32 recyclable = 3;</code>
     * @param value The recyclable to set.
     * @return This builder for chaining.
     */
    public Builder setRecyclable(int value) {
      
      recyclable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 recyclable = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecyclable() {
      
      recyclable_ = 0;
      onChanged();
      return this;
    }

    private int nonRecoverable_ ;
    /**
     * <code>int32 nonRecoverable = 4;</code>
     * @return The nonRecoverable.
     */
    @java.lang.Override
    public int getNonRecoverable() {
      return nonRecoverable_;
    }
    /**
     * <code>int32 nonRecoverable = 4;</code>
     * @param value The nonRecoverable to set.
     * @return This builder for chaining.
     */
    public Builder setNonRecoverable(int value) {
      
      nonRecoverable_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nonRecoverable = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNonRecoverable() {
      
      nonRecoverable_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wasteanalytics.DailySummary)
  }

  // @@protoc_insertion_point(class_scope:wasteanalytics.DailySummary)
  private static final wasteanalytics.DailySummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new wasteanalytics.DailySummary();
  }

  public static wasteanalytics.DailySummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DailySummary>
      PARSER = new com.google.protobuf.AbstractParser<DailySummary>() {
    @java.lang.Override
    public DailySummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DailySummary(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DailySummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DailySummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public wasteanalytics.DailySummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

