// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasteanalytics.proto

package wasteanalytics;

/**
 * Protobuf type {@code wasteanalytics.DailyReport}
 */
public final class DailyReport extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wasteanalytics.DailyReport)
    DailyReportOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DailyReport.newBuilder() to construct.
  private DailyReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DailyReport() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DailyReport();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DailyReport(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            wasteanalytics.DailySummary.Builder subBuilder = null;
            if (dailySummary_ != null) {
              subBuilder = dailySummary_.toBuilder();
            }
            dailySummary_ = input.readMessage(wasteanalytics.DailySummary.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dailySummary_);
              dailySummary_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            wasteanalytics.RecyclingBenefits.Builder subBuilder = null;
            if (recyclingBenefits_ != null) {
              subBuilder = recyclingBenefits_.toBuilder();
            }
            recyclingBenefits_ = input.readMessage(wasteanalytics.RecyclingBenefits.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(recyclingBenefits_);
              recyclingBenefits_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailyReport_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailyReport_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            wasteanalytics.DailyReport.class, wasteanalytics.DailyReport.Builder.class);
  }

  public static final int DAILYSUMMARY_FIELD_NUMBER = 1;
  private wasteanalytics.DailySummary dailySummary_;
  /**
   * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
   * @return Whether the dailySummary field is set.
   */
  @java.lang.Override
  public boolean hasDailySummary() {
    return dailySummary_ != null;
  }
  /**
   * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
   * @return The dailySummary.
   */
  @java.lang.Override
  public wasteanalytics.DailySummary getDailySummary() {
    return dailySummary_ == null ? wasteanalytics.DailySummary.getDefaultInstance() : dailySummary_;
  }
  /**
   * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
   */
  @java.lang.Override
  public wasteanalytics.DailySummaryOrBuilder getDailySummaryOrBuilder() {
    return getDailySummary();
  }

  public static final int RECYCLINGBENEFITS_FIELD_NUMBER = 2;
  private wasteanalytics.RecyclingBenefits recyclingBenefits_;
  /**
   * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
   * @return Whether the recyclingBenefits field is set.
   */
  @java.lang.Override
  public boolean hasRecyclingBenefits() {
    return recyclingBenefits_ != null;
  }
  /**
   * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
   * @return The recyclingBenefits.
   */
  @java.lang.Override
  public wasteanalytics.RecyclingBenefits getRecyclingBenefits() {
    return recyclingBenefits_ == null ? wasteanalytics.RecyclingBenefits.getDefaultInstance() : recyclingBenefits_;
  }
  /**
   * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
   */
  @java.lang.Override
  public wasteanalytics.RecyclingBenefitsOrBuilder getRecyclingBenefitsOrBuilder() {
    return getRecyclingBenefits();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dailySummary_ != null) {
      output.writeMessage(1, getDailySummary());
    }
    if (recyclingBenefits_ != null) {
      output.writeMessage(2, getRecyclingBenefits());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (dailySummary_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getDailySummary());
    }
    if (recyclingBenefits_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getRecyclingBenefits());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof wasteanalytics.DailyReport)) {
      return super.equals(obj);
    }
    wasteanalytics.DailyReport other = (wasteanalytics.DailyReport) obj;

    if (hasDailySummary() != other.hasDailySummary()) return false;
    if (hasDailySummary()) {
      if (!getDailySummary()
          .equals(other.getDailySummary())) return false;
    }
    if (hasRecyclingBenefits() != other.hasRecyclingBenefits()) return false;
    if (hasRecyclingBenefits()) {
      if (!getRecyclingBenefits()
          .equals(other.getRecyclingBenefits())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDailySummary()) {
      hash = (37 * hash) + DAILYSUMMARY_FIELD_NUMBER;
      hash = (53 * hash) + getDailySummary().hashCode();
    }
    if (hasRecyclingBenefits()) {
      hash = (37 * hash) + RECYCLINGBENEFITS_FIELD_NUMBER;
      hash = (53 * hash) + getRecyclingBenefits().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static wasteanalytics.DailyReport parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.DailyReport parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.DailyReport parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.DailyReport parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.DailyReport parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.DailyReport parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.DailyReport parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static wasteanalytics.DailyReport parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static wasteanalytics.DailyReport parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static wasteanalytics.DailyReport parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static wasteanalytics.DailyReport parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static wasteanalytics.DailyReport parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(wasteanalytics.DailyReport prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wasteanalytics.DailyReport}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wasteanalytics.DailyReport)
      wasteanalytics.DailyReportOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailyReport_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailyReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wasteanalytics.DailyReport.class, wasteanalytics.DailyReport.Builder.class);
    }

    // Construct using wasteanalytics.DailyReport.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dailySummaryBuilder_ == null) {
        dailySummary_ = null;
      } else {
        dailySummary_ = null;
        dailySummaryBuilder_ = null;
      }
      if (recyclingBenefitsBuilder_ == null) {
        recyclingBenefits_ = null;
      } else {
        recyclingBenefits_ = null;
        recyclingBenefitsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_DailyReport_descriptor;
    }

    @java.lang.Override
    public wasteanalytics.DailyReport getDefaultInstanceForType() {
      return wasteanalytics.DailyReport.getDefaultInstance();
    }

    @java.lang.Override
    public wasteanalytics.DailyReport build() {
      wasteanalytics.DailyReport result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public wasteanalytics.DailyReport buildPartial() {
      wasteanalytics.DailyReport result = new wasteanalytics.DailyReport(this);
      if (dailySummaryBuilder_ == null) {
        result.dailySummary_ = dailySummary_;
      } else {
        result.dailySummary_ = dailySummaryBuilder_.build();
      }
      if (recyclingBenefitsBuilder_ == null) {
        result.recyclingBenefits_ = recyclingBenefits_;
      } else {
        result.recyclingBenefits_ = recyclingBenefitsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof wasteanalytics.DailyReport) {
        return mergeFrom((wasteanalytics.DailyReport)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(wasteanalytics.DailyReport other) {
      if (other == wasteanalytics.DailyReport.getDefaultInstance()) return this;
      if (other.hasDailySummary()) {
        mergeDailySummary(other.getDailySummary());
      }
      if (other.hasRecyclingBenefits()) {
        mergeRecyclingBenefits(other.getRecyclingBenefits());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      wasteanalytics.DailyReport parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (wasteanalytics.DailyReport) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private wasteanalytics.DailySummary dailySummary_;
    private com.google.protobuf.SingleFieldBuilderV3<
        wasteanalytics.DailySummary, wasteanalytics.DailySummary.Builder, wasteanalytics.DailySummaryOrBuilder> dailySummaryBuilder_;
    /**
     * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
     * @return Whether the dailySummary field is set.
     */
    public boolean hasDailySummary() {
      return dailySummaryBuilder_ != null || dailySummary_ != null;
    }
    /**
     * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
     * @return The dailySummary.
     */
    public wasteanalytics.DailySummary getDailySummary() {
      if (dailySummaryBuilder_ == null) {
        return dailySummary_ == null ? wasteanalytics.DailySummary.getDefaultInstance() : dailySummary_;
      } else {
        return dailySummaryBuilder_.getMessage();
      }
    }
    /**
     * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
     */
    public Builder setDailySummary(wasteanalytics.DailySummary value) {
      if (dailySummaryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dailySummary_ = value;
        onChanged();
      } else {
        dailySummaryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
     */
    public Builder setDailySummary(
        wasteanalytics.DailySummary.Builder builderForValue) {
      if (dailySummaryBuilder_ == null) {
        dailySummary_ = builderForValue.build();
        onChanged();
      } else {
        dailySummaryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
     */
    public Builder mergeDailySummary(wasteanalytics.DailySummary value) {
      if (dailySummaryBuilder_ == null) {
        if (dailySummary_ != null) {
          dailySummary_ =
            wasteanalytics.DailySummary.newBuilder(dailySummary_).mergeFrom(value).buildPartial();
        } else {
          dailySummary_ = value;
        }
        onChanged();
      } else {
        dailySummaryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
     */
    public Builder clearDailySummary() {
      if (dailySummaryBuilder_ == null) {
        dailySummary_ = null;
        onChanged();
      } else {
        dailySummary_ = null;
        dailySummaryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
     */
    public wasteanalytics.DailySummary.Builder getDailySummaryBuilder() {
      
      onChanged();
      return getDailySummaryFieldBuilder().getBuilder();
    }
    /**
     * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
     */
    public wasteanalytics.DailySummaryOrBuilder getDailySummaryOrBuilder() {
      if (dailySummaryBuilder_ != null) {
        return dailySummaryBuilder_.getMessageOrBuilder();
      } else {
        return dailySummary_ == null ?
            wasteanalytics.DailySummary.getDefaultInstance() : dailySummary_;
      }
    }
    /**
     * <code>.wasteanalytics.DailySummary dailySummary = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        wasteanalytics.DailySummary, wasteanalytics.DailySummary.Builder, wasteanalytics.DailySummaryOrBuilder> 
        getDailySummaryFieldBuilder() {
      if (dailySummaryBuilder_ == null) {
        dailySummaryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            wasteanalytics.DailySummary, wasteanalytics.DailySummary.Builder, wasteanalytics.DailySummaryOrBuilder>(
                getDailySummary(),
                getParentForChildren(),
                isClean());
        dailySummary_ = null;
      }
      return dailySummaryBuilder_;
    }

    private wasteanalytics.RecyclingBenefits recyclingBenefits_;
    private com.google.protobuf.SingleFieldBuilderV3<
        wasteanalytics.RecyclingBenefits, wasteanalytics.RecyclingBenefits.Builder, wasteanalytics.RecyclingBenefitsOrBuilder> recyclingBenefitsBuilder_;
    /**
     * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
     * @return Whether the recyclingBenefits field is set.
     */
    public boolean hasRecyclingBenefits() {
      return recyclingBenefitsBuilder_ != null || recyclingBenefits_ != null;
    }
    /**
     * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
     * @return The recyclingBenefits.
     */
    public wasteanalytics.RecyclingBenefits getRecyclingBenefits() {
      if (recyclingBenefitsBuilder_ == null) {
        return recyclingBenefits_ == null ? wasteanalytics.RecyclingBenefits.getDefaultInstance() : recyclingBenefits_;
      } else {
        return recyclingBenefitsBuilder_.getMessage();
      }
    }
    /**
     * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
     */
    public Builder setRecyclingBenefits(wasteanalytics.RecyclingBenefits value) {
      if (recyclingBenefitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        recyclingBenefits_ = value;
        onChanged();
      } else {
        recyclingBenefitsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
     */
    public Builder setRecyclingBenefits(
        wasteanalytics.RecyclingBenefits.Builder builderForValue) {
      if (recyclingBenefitsBuilder_ == null) {
        recyclingBenefits_ = builderForValue.build();
        onChanged();
      } else {
        recyclingBenefitsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
     */
    public Builder mergeRecyclingBenefits(wasteanalytics.RecyclingBenefits value) {
      if (recyclingBenefitsBuilder_ == null) {
        if (recyclingBenefits_ != null) {
          recyclingBenefits_ =
            wasteanalytics.RecyclingBenefits.newBuilder(recyclingBenefits_).mergeFrom(value).buildPartial();
        } else {
          recyclingBenefits_ = value;
        }
        onChanged();
      } else {
        recyclingBenefitsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
     */
    public Builder clearRecyclingBenefits() {
      if (recyclingBenefitsBuilder_ == null) {
        recyclingBenefits_ = null;
        onChanged();
      } else {
        recyclingBenefits_ = null;
        recyclingBenefitsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
     */
    public wasteanalytics.RecyclingBenefits.Builder getRecyclingBenefitsBuilder() {
      
      onChanged();
      return getRecyclingBenefitsFieldBuilder().getBuilder();
    }
    /**
     * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
     */
    public wasteanalytics.RecyclingBenefitsOrBuilder getRecyclingBenefitsOrBuilder() {
      if (recyclingBenefitsBuilder_ != null) {
        return recyclingBenefitsBuilder_.getMessageOrBuilder();
      } else {
        return recyclingBenefits_ == null ?
            wasteanalytics.RecyclingBenefits.getDefaultInstance() : recyclingBenefits_;
      }
    }
    /**
     * <code>.wasteanalytics.RecyclingBenefits recyclingBenefits = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        wasteanalytics.RecyclingBenefits, wasteanalytics.RecyclingBenefits.Builder, wasteanalytics.RecyclingBenefitsOrBuilder> 
        getRecyclingBenefitsFieldBuilder() {
      if (recyclingBenefitsBuilder_ == null) {
        recyclingBenefitsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            wasteanalytics.RecyclingBenefits, wasteanalytics.RecyclingBenefits.Builder, wasteanalytics.RecyclingBenefitsOrBuilder>(
                getRecyclingBenefits(),
                getParentForChildren(),
                isClean());
        recyclingBenefits_ = null;
      }
      return recyclingBenefitsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wasteanalytics.DailyReport)
  }

  // @@protoc_insertion_point(class_scope:wasteanalytics.DailyReport)
  private static final wasteanalytics.DailyReport DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new wasteanalytics.DailyReport();
  }

  public static wasteanalytics.DailyReport getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DailyReport>
      PARSER = new com.google.protobuf.AbstractParser<DailyReport>() {
    @java.lang.Override
    public DailyReport parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DailyReport(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DailyReport> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DailyReport> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public wasteanalytics.DailyReport getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

