// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasteanalytics.proto

package wasteanalytics;

/**
 * Protobuf type {@code wasteanalytics.RecyclingBenefits}
 */
public final class RecyclingBenefits extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wasteanalytics.RecyclingBenefits)
    RecyclingBenefitsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecyclingBenefits.newBuilder() to construct.
  private RecyclingBenefits(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecyclingBenefits() {
    estimatedSavings_ = "";
    wasteDivertedFromLandfill_ = "";
    tip_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RecyclingBenefits();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecyclingBenefits(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            reusedBySoltex_ = input.readInt32();
            break;
          }
          case 16: {

            recycledCones_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            estimatedSavings_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            wasteDivertedFromLandfill_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            tip_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_RecyclingBenefits_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_RecyclingBenefits_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            wasteanalytics.RecyclingBenefits.class, wasteanalytics.RecyclingBenefits.Builder.class);
  }

  public static final int REUSEDBYSOLTEX_FIELD_NUMBER = 1;
  private int reusedBySoltex_;
  /**
   * <code>int32 reusedBySoltex = 1;</code>
   * @return The reusedBySoltex.
   */
  @java.lang.Override
  public int getReusedBySoltex() {
    return reusedBySoltex_;
  }

  public static final int RECYCLEDCONES_FIELD_NUMBER = 2;
  private int recycledCones_;
  /**
   * <code>int32 recycledCones = 2;</code>
   * @return The recycledCones.
   */
  @java.lang.Override
  public int getRecycledCones() {
    return recycledCones_;
  }

  public static final int ESTIMATEDSAVINGS_FIELD_NUMBER = 3;
  private volatile java.lang.Object estimatedSavings_;
  /**
   * <pre>
   * e.g., "14000 gs"
   * </pre>
   *
   * <code>string estimatedSavings = 3;</code>
   * @return The estimatedSavings.
   */
  @java.lang.Override
  public java.lang.String getEstimatedSavings() {
    java.lang.Object ref = estimatedSavings_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      estimatedSavings_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g., "14000 gs"
   * </pre>
   *
   * <code>string estimatedSavings = 3;</code>
   * @return The bytes for estimatedSavings.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEstimatedSavingsBytes() {
    java.lang.Object ref = estimatedSavings_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      estimatedSavings_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WASTEDIVERTEDFROMLANDFILL_FIELD_NUMBER = 4;
  private volatile java.lang.Object wasteDivertedFromLandfill_;
  /**
   * <pre>
   * e.g., "75%"
   * </pre>
   *
   * <code>string wasteDivertedFromLandfill = 4;</code>
   * @return The wasteDivertedFromLandfill.
   */
  @java.lang.Override
  public java.lang.String getWasteDivertedFromLandfill() {
    java.lang.Object ref = wasteDivertedFromLandfill_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wasteDivertedFromLandfill_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g., "75%"
   * </pre>
   *
   * <code>string wasteDivertedFromLandfill = 4;</code>
   * @return The bytes for wasteDivertedFromLandfill.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWasteDivertedFromLandfillBytes() {
    java.lang.Object ref = wasteDivertedFromLandfill_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wasteDivertedFromLandfill_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIP_FIELD_NUMBER = 5;
  private volatile java.lang.Object tip_;
  /**
   * <code>string tip = 5;</code>
   * @return The tip.
   */
  @java.lang.Override
  public java.lang.String getTip() {
    java.lang.Object ref = tip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tip_ = s;
      return s;
    }
  }
  /**
   * <code>string tip = 5;</code>
   * @return The bytes for tip.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTipBytes() {
    java.lang.Object ref = tip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reusedBySoltex_ != 0) {
      output.writeInt32(1, reusedBySoltex_);
    }
    if (recycledCones_ != 0) {
      output.writeInt32(2, recycledCones_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(estimatedSavings_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, estimatedSavings_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wasteDivertedFromLandfill_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, wasteDivertedFromLandfill_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tip_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tip_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reusedBySoltex_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, reusedBySoltex_);
    }
    if (recycledCones_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, recycledCones_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(estimatedSavings_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, estimatedSavings_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wasteDivertedFromLandfill_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, wasteDivertedFromLandfill_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tip_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tip_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof wasteanalytics.RecyclingBenefits)) {
      return super.equals(obj);
    }
    wasteanalytics.RecyclingBenefits other = (wasteanalytics.RecyclingBenefits) obj;

    if (getReusedBySoltex()
        != other.getReusedBySoltex()) return false;
    if (getRecycledCones()
        != other.getRecycledCones()) return false;
    if (!getEstimatedSavings()
        .equals(other.getEstimatedSavings())) return false;
    if (!getWasteDivertedFromLandfill()
        .equals(other.getWasteDivertedFromLandfill())) return false;
    if (!getTip()
        .equals(other.getTip())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REUSEDBYSOLTEX_FIELD_NUMBER;
    hash = (53 * hash) + getReusedBySoltex();
    hash = (37 * hash) + RECYCLEDCONES_FIELD_NUMBER;
    hash = (53 * hash) + getRecycledCones();
    hash = (37 * hash) + ESTIMATEDSAVINGS_FIELD_NUMBER;
    hash = (53 * hash) + getEstimatedSavings().hashCode();
    hash = (37 * hash) + WASTEDIVERTEDFROMLANDFILL_FIELD_NUMBER;
    hash = (53 * hash) + getWasteDivertedFromLandfill().hashCode();
    hash = (37 * hash) + TIP_FIELD_NUMBER;
    hash = (53 * hash) + getTip().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static wasteanalytics.RecyclingBenefits parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.RecyclingBenefits parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.RecyclingBenefits parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.RecyclingBenefits parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.RecyclingBenefits parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.RecyclingBenefits parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.RecyclingBenefits parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static wasteanalytics.RecyclingBenefits parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static wasteanalytics.RecyclingBenefits parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static wasteanalytics.RecyclingBenefits parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static wasteanalytics.RecyclingBenefits parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static wasteanalytics.RecyclingBenefits parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(wasteanalytics.RecyclingBenefits prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wasteanalytics.RecyclingBenefits}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wasteanalytics.RecyclingBenefits)
      wasteanalytics.RecyclingBenefitsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_RecyclingBenefits_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_RecyclingBenefits_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wasteanalytics.RecyclingBenefits.class, wasteanalytics.RecyclingBenefits.Builder.class);
    }

    // Construct using wasteanalytics.RecyclingBenefits.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reusedBySoltex_ = 0;

      recycledCones_ = 0;

      estimatedSavings_ = "";

      wasteDivertedFromLandfill_ = "";

      tip_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_RecyclingBenefits_descriptor;
    }

    @java.lang.Override
    public wasteanalytics.RecyclingBenefits getDefaultInstanceForType() {
      return wasteanalytics.RecyclingBenefits.getDefaultInstance();
    }

    @java.lang.Override
    public wasteanalytics.RecyclingBenefits build() {
      wasteanalytics.RecyclingBenefits result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public wasteanalytics.RecyclingBenefits buildPartial() {
      wasteanalytics.RecyclingBenefits result = new wasteanalytics.RecyclingBenefits(this);
      result.reusedBySoltex_ = reusedBySoltex_;
      result.recycledCones_ = recycledCones_;
      result.estimatedSavings_ = estimatedSavings_;
      result.wasteDivertedFromLandfill_ = wasteDivertedFromLandfill_;
      result.tip_ = tip_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof wasteanalytics.RecyclingBenefits) {
        return mergeFrom((wasteanalytics.RecyclingBenefits)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(wasteanalytics.RecyclingBenefits other) {
      if (other == wasteanalytics.RecyclingBenefits.getDefaultInstance()) return this;
      if (other.getReusedBySoltex() != 0) {
        setReusedBySoltex(other.getReusedBySoltex());
      }
      if (other.getRecycledCones() != 0) {
        setRecycledCones(other.getRecycledCones());
      }
      if (!other.getEstimatedSavings().isEmpty()) {
        estimatedSavings_ = other.estimatedSavings_;
        onChanged();
      }
      if (!other.getWasteDivertedFromLandfill().isEmpty()) {
        wasteDivertedFromLandfill_ = other.wasteDivertedFromLandfill_;
        onChanged();
      }
      if (!other.getTip().isEmpty()) {
        tip_ = other.tip_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      wasteanalytics.RecyclingBenefits parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (wasteanalytics.RecyclingBenefits) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int reusedBySoltex_ ;
    /**
     * <code>int32 reusedBySoltex = 1;</code>
     * @return The reusedBySoltex.
     */
    @java.lang.Override
    public int getReusedBySoltex() {
      return reusedBySoltex_;
    }
    /**
     * <code>int32 reusedBySoltex = 1;</code>
     * @param value The reusedBySoltex to set.
     * @return This builder for chaining.
     */
    public Builder setReusedBySoltex(int value) {
      
      reusedBySoltex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 reusedBySoltex = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReusedBySoltex() {
      
      reusedBySoltex_ = 0;
      onChanged();
      return this;
    }

    private int recycledCones_ ;
    /**
     * <code>int32 recycledCones = 2;</code>
     * @return The recycledCones.
     */
    @java.lang.Override
    public int getRecycledCones() {
      return recycledCones_;
    }
    /**
     * <code>int32 recycledCones = 2;</code>
     * @param value The recycledCones to set.
     * @return This builder for chaining.
     */
    public Builder setRecycledCones(int value) {
      
      recycledCones_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 recycledCones = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecycledCones() {
      
      recycledCones_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object estimatedSavings_ = "";
    /**
     * <pre>
     * e.g., "14000 gs"
     * </pre>
     *
     * <code>string estimatedSavings = 3;</code>
     * @return The estimatedSavings.
     */
    public java.lang.String getEstimatedSavings() {
      java.lang.Object ref = estimatedSavings_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        estimatedSavings_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g., "14000 gs"
     * </pre>
     *
     * <code>string estimatedSavings = 3;</code>
     * @return The bytes for estimatedSavings.
     */
    public com.google.protobuf.ByteString
        getEstimatedSavingsBytes() {
      java.lang.Object ref = estimatedSavings_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        estimatedSavings_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g., "14000 gs"
     * </pre>
     *
     * <code>string estimatedSavings = 3;</code>
     * @param value The estimatedSavings to set.
     * @return This builder for chaining.
     */
    public Builder setEstimatedSavings(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      estimatedSavings_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "14000 gs"
     * </pre>
     *
     * <code>string estimatedSavings = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEstimatedSavings() {
      
      estimatedSavings_ = getDefaultInstance().getEstimatedSavings();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "14000 gs"
     * </pre>
     *
     * <code>string estimatedSavings = 3;</code>
     * @param value The bytes for estimatedSavings to set.
     * @return This builder for chaining.
     */
    public Builder setEstimatedSavingsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      estimatedSavings_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object wasteDivertedFromLandfill_ = "";
    /**
     * <pre>
     * e.g., "75%"
     * </pre>
     *
     * <code>string wasteDivertedFromLandfill = 4;</code>
     * @return The wasteDivertedFromLandfill.
     */
    public java.lang.String getWasteDivertedFromLandfill() {
      java.lang.Object ref = wasteDivertedFromLandfill_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wasteDivertedFromLandfill_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g., "75%"
     * </pre>
     *
     * <code>string wasteDivertedFromLandfill = 4;</code>
     * @return The bytes for wasteDivertedFromLandfill.
     */
    public com.google.protobuf.ByteString
        getWasteDivertedFromLandfillBytes() {
      java.lang.Object ref = wasteDivertedFromLandfill_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wasteDivertedFromLandfill_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g., "75%"
     * </pre>
     *
     * <code>string wasteDivertedFromLandfill = 4;</code>
     * @param value The wasteDivertedFromLandfill to set.
     * @return This builder for chaining.
     */
    public Builder setWasteDivertedFromLandfill(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wasteDivertedFromLandfill_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "75%"
     * </pre>
     *
     * <code>string wasteDivertedFromLandfill = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWasteDivertedFromLandfill() {
      
      wasteDivertedFromLandfill_ = getDefaultInstance().getWasteDivertedFromLandfill();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "75%"
     * </pre>
     *
     * <code>string wasteDivertedFromLandfill = 4;</code>
     * @param value The bytes for wasteDivertedFromLandfill to set.
     * @return This builder for chaining.
     */
    public Builder setWasteDivertedFromLandfillBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wasteDivertedFromLandfill_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tip_ = "";
    /**
     * <code>string tip = 5;</code>
     * @return The tip.
     */
    public java.lang.String getTip() {
      java.lang.Object ref = tip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tip = 5;</code>
     * @return The bytes for tip.
     */
    public com.google.protobuf.ByteString
        getTipBytes() {
      java.lang.Object ref = tip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tip = 5;</code>
     * @param value The tip to set.
     * @return This builder for chaining.
     */
    public Builder setTip(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tip = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTip() {
      
      tip_ = getDefaultInstance().getTip();
      onChanged();
      return this;
    }
    /**
     * <code>string tip = 5;</code>
     * @param value The bytes for tip to set.
     * @return This builder for chaining.
     */
    public Builder setTipBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tip_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wasteanalytics.RecyclingBenefits)
  }

  // @@protoc_insertion_point(class_scope:wasteanalytics.RecyclingBenefits)
  private static final wasteanalytics.RecyclingBenefits DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new wasteanalytics.RecyclingBenefits();
  }

  public static wasteanalytics.RecyclingBenefits getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecyclingBenefits>
      PARSER = new com.google.protobuf.AbstractParser<RecyclingBenefits>() {
    @java.lang.Override
    public RecyclingBenefits parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RecyclingBenefits(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecyclingBenefits> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecyclingBenefits> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public wasteanalytics.RecyclingBenefits getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

