// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasteanalytics.proto

package wasteanalytics;

public interface RecyclingBenefitsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wasteanalytics.RecyclingBenefits)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reusedBySoltex = 1;</code>
   * @return The reusedBySoltex.
   */
  int getReusedBySoltex();

  /**
   * <code>int32 recycledCones = 2;</code>
   * @return The recycledCones.
   */
  int getRecycledCones();

  /**
   * <pre>
   * e.g., "14000 gs"
   * </pre>
   *
   * <code>string estimatedSavings = 3;</code>
   * @return The estimatedSavings.
   */
  java.lang.String getEstimatedSavings();
  /**
   * <pre>
   * e.g., "14000 gs"
   * </pre>
   *
   * <code>string estimatedSavings = 3;</code>
   * @return The bytes for estimatedSavings.
   */
  com.google.protobuf.ByteString
      getEstimatedSavingsBytes();

  /**
   * <pre>
   * e.g., "75%"
   * </pre>
   *
   * <code>string wasteDivertedFromLandfill = 4;</code>
   * @return The wasteDivertedFromLandfill.
   */
  java.lang.String getWasteDivertedFromLandfill();
  /**
   * <pre>
   * e.g., "75%"
   * </pre>
   *
   * <code>string wasteDivertedFromLandfill = 4;</code>
   * @return The bytes for wasteDivertedFromLandfill.
   */
  com.google.protobuf.ByteString
      getWasteDivertedFromLandfillBytes();

  /**
   * <code>string tip = 5;</code>
   * @return The tip.
   */
  java.lang.String getTip();
  /**
   * <code>string tip = 5;</code>
   * @return The bytes for tip.
   */
  com.google.protobuf.ByteString
      getTipBytes();
}
