// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasteanalytics.proto

package wasteanalytics;

public interface WasteRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wasteanalytics.WasteRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "plastic", "cardboard"
   * </pre>
   *
   * <code>string material = 1;</code>
   * @return The material.
   */
  java.lang.String getMaterial();
  /**
   * <pre>
   * "plastic", "cardboard"
   * </pre>
   *
   * <code>string material = 1;</code>
   * @return The bytes for material.
   */
  com.google.protobuf.ByteString
      getMaterialBytes();

  /**
   * <pre>
   * "good", "damaged"
   * </pre>
   *
   * <code>string condition = 2;</code>
   * @return The condition.
   */
  java.lang.String getCondition();
  /**
   * <pre>
   * "good", "damaged"
   * </pre>
   *
   * <code>string condition = 2;</code>
   * @return The bytes for condition.
   */
  com.google.protobuf.ByteString
      getConditionBytes();

  /**
   * <pre>
   * "small", "large"
   * </pre>
   *
   * <code>string size = 3;</code>
   * @return The size.
   */
  java.lang.String getSize();
  /**
   * <pre>
   * "small", "large"
   * </pre>
   *
   * <code>string size = 3;</code>
   * @return The bytes for size.
   */
  com.google.protobuf.ByteString
      getSizeBytes();

  /**
   * <pre>
   * e.g., "2025-07-06"
   * </pre>
   *
   * <code>string date = 4;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <pre>
   * e.g., "2025-07-06"
   * </pre>
   *
   * <code>string date = 4;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
