// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasteanalytics.proto

package wasteanalytics;

/**
 * Protobuf type {@code wasteanalytics.WasteRecord}
 */
public final class WasteRecord extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wasteanalytics.WasteRecord)
    WasteRecordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WasteRecord.newBuilder() to construct.
  private WasteRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WasteRecord() {
    material_ = "";
    condition_ = "";
    size_ = "";
    date_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WasteRecord();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WasteRecord(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            material_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            condition_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            size_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            date_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_WasteRecord_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_WasteRecord_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            wasteanalytics.WasteRecord.class, wasteanalytics.WasteRecord.Builder.class);
  }

  public static final int MATERIAL_FIELD_NUMBER = 1;
  private volatile java.lang.Object material_;
  /**
   * <pre>
   * "plastic", "cardboard"
   * </pre>
   *
   * <code>string material = 1;</code>
   * @return The material.
   */
  @java.lang.Override
  public java.lang.String getMaterial() {
    java.lang.Object ref = material_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      material_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "plastic", "cardboard"
   * </pre>
   *
   * <code>string material = 1;</code>
   * @return The bytes for material.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMaterialBytes() {
    java.lang.Object ref = material_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      material_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONDITION_FIELD_NUMBER = 2;
  private volatile java.lang.Object condition_;
  /**
   * <pre>
   * "good", "damaged"
   * </pre>
   *
   * <code>string condition = 2;</code>
   * @return The condition.
   */
  @java.lang.Override
  public java.lang.String getCondition() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      condition_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "good", "damaged"
   * </pre>
   *
   * <code>string condition = 2;</code>
   * @return The bytes for condition.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConditionBytes() {
    java.lang.Object ref = condition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      condition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private volatile java.lang.Object size_;
  /**
   * <pre>
   * "small", "large"
   * </pre>
   *
   * <code>string size = 3;</code>
   * @return The size.
   */
  @java.lang.Override
  public java.lang.String getSize() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      size_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * "small", "large"
   * </pre>
   *
   * <code>string size = 3;</code>
   * @return The bytes for size.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSizeBytes() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      size_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object date_;
  /**
   * <pre>
   * e.g., "2025-07-06"
   * </pre>
   *
   * <code>string date = 4;</code>
   * @return The date.
   */
  @java.lang.Override
  public java.lang.String getDate() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      date_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g., "2025-07-06"
   * </pre>
   *
   * <code>string date = 4;</code>
   * @return The bytes for date.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDateBytes() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(material_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, material_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(condition_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, condition_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(size_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, date_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(material_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, material_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(condition_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, condition_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(size_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, size_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(date_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, date_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof wasteanalytics.WasteRecord)) {
      return super.equals(obj);
    }
    wasteanalytics.WasteRecord other = (wasteanalytics.WasteRecord) obj;

    if (!getMaterial()
        .equals(other.getMaterial())) return false;
    if (!getCondition()
        .equals(other.getCondition())) return false;
    if (!getSize()
        .equals(other.getSize())) return false;
    if (!getDate()
        .equals(other.getDate())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MATERIAL_FIELD_NUMBER;
    hash = (53 * hash) + getMaterial().hashCode();
    hash = (37 * hash) + CONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getCondition().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize().hashCode();
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static wasteanalytics.WasteRecord parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.WasteRecord parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.WasteRecord parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.WasteRecord parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.WasteRecord parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static wasteanalytics.WasteRecord parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static wasteanalytics.WasteRecord parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static wasteanalytics.WasteRecord parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static wasteanalytics.WasteRecord parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static wasteanalytics.WasteRecord parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static wasteanalytics.WasteRecord parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static wasteanalytics.WasteRecord parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(wasteanalytics.WasteRecord prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wasteanalytics.WasteRecord}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wasteanalytics.WasteRecord)
      wasteanalytics.WasteRecordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_WasteRecord_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_WasteRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              wasteanalytics.WasteRecord.class, wasteanalytics.WasteRecord.Builder.class);
    }

    // Construct using wasteanalytics.WasteRecord.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      material_ = "";

      condition_ = "";

      size_ = "";

      date_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return wasteanalytics.Wasteanalytics.internal_static_wasteanalytics_WasteRecord_descriptor;
    }

    @java.lang.Override
    public wasteanalytics.WasteRecord getDefaultInstanceForType() {
      return wasteanalytics.WasteRecord.getDefaultInstance();
    }

    @java.lang.Override
    public wasteanalytics.WasteRecord build() {
      wasteanalytics.WasteRecord result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public wasteanalytics.WasteRecord buildPartial() {
      wasteanalytics.WasteRecord result = new wasteanalytics.WasteRecord(this);
      result.material_ = material_;
      result.condition_ = condition_;
      result.size_ = size_;
      result.date_ = date_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof wasteanalytics.WasteRecord) {
        return mergeFrom((wasteanalytics.WasteRecord)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(wasteanalytics.WasteRecord other) {
      if (other == wasteanalytics.WasteRecord.getDefaultInstance()) return this;
      if (!other.getMaterial().isEmpty()) {
        material_ = other.material_;
        onChanged();
      }
      if (!other.getCondition().isEmpty()) {
        condition_ = other.condition_;
        onChanged();
      }
      if (!other.getSize().isEmpty()) {
        size_ = other.size_;
        onChanged();
      }
      if (!other.getDate().isEmpty()) {
        date_ = other.date_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      wasteanalytics.WasteRecord parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (wasteanalytics.WasteRecord) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object material_ = "";
    /**
     * <pre>
     * "plastic", "cardboard"
     * </pre>
     *
     * <code>string material = 1;</code>
     * @return The material.
     */
    public java.lang.String getMaterial() {
      java.lang.Object ref = material_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        material_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "plastic", "cardboard"
     * </pre>
     *
     * <code>string material = 1;</code>
     * @return The bytes for material.
     */
    public com.google.protobuf.ByteString
        getMaterialBytes() {
      java.lang.Object ref = material_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        material_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "plastic", "cardboard"
     * </pre>
     *
     * <code>string material = 1;</code>
     * @param value The material to set.
     * @return This builder for chaining.
     */
    public Builder setMaterial(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      material_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "plastic", "cardboard"
     * </pre>
     *
     * <code>string material = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaterial() {
      
      material_ = getDefaultInstance().getMaterial();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "plastic", "cardboard"
     * </pre>
     *
     * <code>string material = 1;</code>
     * @param value The bytes for material to set.
     * @return This builder for chaining.
     */
    public Builder setMaterialBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      material_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object condition_ = "";
    /**
     * <pre>
     * "good", "damaged"
     * </pre>
     *
     * <code>string condition = 2;</code>
     * @return The condition.
     */
    public java.lang.String getCondition() {
      java.lang.Object ref = condition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        condition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "good", "damaged"
     * </pre>
     *
     * <code>string condition = 2;</code>
     * @return The bytes for condition.
     */
    public com.google.protobuf.ByteString
        getConditionBytes() {
      java.lang.Object ref = condition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        condition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "good", "damaged"
     * </pre>
     *
     * <code>string condition = 2;</code>
     * @param value The condition to set.
     * @return This builder for chaining.
     */
    public Builder setCondition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      condition_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "good", "damaged"
     * </pre>
     *
     * <code>string condition = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCondition() {
      
      condition_ = getDefaultInstance().getCondition();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "good", "damaged"
     * </pre>
     *
     * <code>string condition = 2;</code>
     * @param value The bytes for condition to set.
     * @return This builder for chaining.
     */
    public Builder setConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      condition_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object size_ = "";
    /**
     * <pre>
     * "small", "large"
     * </pre>
     *
     * <code>string size = 3;</code>
     * @return The size.
     */
    public java.lang.String getSize() {
      java.lang.Object ref = size_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        size_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * "small", "large"
     * </pre>
     *
     * <code>string size = 3;</code>
     * @return The bytes for size.
     */
    public com.google.protobuf.ByteString
        getSizeBytes() {
      java.lang.Object ref = size_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        size_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * "small", "large"
     * </pre>
     *
     * <code>string size = 3;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "small", "large"
     * </pre>
     *
     * <code>string size = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      
      size_ = getDefaultInstance().getSize();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * "small", "large"
     * </pre>
     *
     * <code>string size = 3;</code>
     * @param value The bytes for size to set.
     * @return This builder for chaining.
     */
    public Builder setSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      size_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object date_ = "";
    /**
     * <pre>
     * e.g., "2025-07-06"
     * </pre>
     *
     * <code>string date = 4;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g., "2025-07-06"
     * </pre>
     *
     * <code>string date = 4;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g., "2025-07-06"
     * </pre>
     *
     * <code>string date = 4;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "2025-07-06"
     * </pre>
     *
     * <code>string date = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      
      date_ = getDefaultInstance().getDate();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "2025-07-06"
     * </pre>
     *
     * <code>string date = 4;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      date_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wasteanalytics.WasteRecord)
  }

  // @@protoc_insertion_point(class_scope:wasteanalytics.WasteRecord)
  private static final wasteanalytics.WasteRecord DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new wasteanalytics.WasteRecord();
  }

  public static wasteanalytics.WasteRecord getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WasteRecord>
      PARSER = new com.google.protobuf.AbstractParser<WasteRecord>() {
    @java.lang.Override
    public WasteRecord parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WasteRecord(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WasteRecord> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WasteRecord> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public wasteanalytics.WasteRecord getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

