// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wasteanalytics.proto

package wasteanalytics;

public final class Wasteanalytics {
  private Wasteanalytics() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wasteanalytics_WasteRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wasteanalytics_WasteRecord_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wasteanalytics_DailyReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wasteanalytics_DailyReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wasteanalytics_DailySummary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wasteanalytics_DailySummary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wasteanalytics_RecyclingBenefits_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wasteanalytics_RecyclingBenefits_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024wasteanalytics.proto\022\016wasteanalytics\"N" +
      "\n\013WasteRecord\022\020\n\010material\030\001 \001(\t\022\021\n\tcondi" +
      "tion\030\002 \001(\t\022\014\n\004size\030\003 \001(\t\022\014\n\004date\030\004 \001(\t\"\177" +
      "\n\013DailyReport\0222\n\014dailySummary\030\001 \001(\0132\034.wa" +
      "steanalytics.DailySummary\022<\n\021recyclingBe" +
      "nefits\030\002 \001(\0132!.wasteanalytics.RecyclingB" +
      "enefits\"g\n\014DailySummary\022\022\n\ntotalWaste\030\001 " +
      "\001(\005\022\027\n\017eligibleForSale\030\002 \001(\005\022\022\n\nrecyclab" +
      "le\030\003 \001(\005\022\026\n\016nonRecoverable\030\004 \001(\005\"\214\001\n\021Rec" +
      "yclingBenefits\022\026\n\016reusedBySoltex\030\001 \001(\005\022\025" +
      "\n\rrecycledCones\030\002 \001(\005\022\030\n\020estimatedSaving" +
      "s\030\003 \001(\t\022!\n\031wasteDivertedFromLandfill\030\004 \001" +
      "(\t\022\013\n\003tip\030\005 \001(\t2g\n\025WasteAnalyticsService" +
      "\022N\n\020SubmitDailyWaste\022\033.wasteanalytics.Wa" +
      "steRecord\032\033.wasteanalytics.DailyReport(\001" +
      "B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_wasteanalytics_WasteRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wasteanalytics_WasteRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wasteanalytics_WasteRecord_descriptor,
        new java.lang.String[] { "Material", "Condition", "Size", "Date", });
    internal_static_wasteanalytics_DailyReport_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wasteanalytics_DailyReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wasteanalytics_DailyReport_descriptor,
        new java.lang.String[] { "DailySummary", "RecyclingBenefits", });
    internal_static_wasteanalytics_DailySummary_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_wasteanalytics_DailySummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wasteanalytics_DailySummary_descriptor,
        new java.lang.String[] { "TotalWaste", "EligibleForSale", "Recyclable", "NonRecoverable", });
    internal_static_wasteanalytics_RecyclingBenefits_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_wasteanalytics_RecyclingBenefits_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wasteanalytics_RecyclingBenefits_descriptor,
        new java.lang.String[] { "ReusedBySoltex", "RecycledCones", "EstimatedSavings", "WasteDivertedFromLandfill", "Tip", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
