// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coneclassification.proto

package coneclassification;

public interface ConeInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coneclassification.ConeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * "plastic" or "cardboard"
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * "plastic" or "cardboard"
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * "small" or "large"
   * </pre>
   *
   * <code>string size = 2;</code>
   * @return The size.
   */
  java.lang.String getSize();
  /**
   * <pre>
   * "small" or "large"
   * </pre>
   *
   * <code>string size = 2;</code>
   * @return The bytes for size.
   */
  com.google.protobuf.ByteString
      getSizeBytes();

  /**
   * <pre>
   * "good" or "damaged"
   * </pre>
   *
   * <code>string condition = 3;</code>
   * @return The condition.
   */
  java.lang.String getCondition();
  /**
   * <pre>
   * "good" or "damaged"
   * </pre>
   *
   * <code>string condition = 3;</code>
   * @return The bytes for condition.
   */
  com.google.protobuf.ByteString
      getConditionBytes();
}
