// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coneclassification.proto

package coneclassification;

public final class Coneclassification {
  private Coneclassification() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coneclassification_ConeInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coneclassification_ConeInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coneclassification_Suggestion_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coneclassification_Suggestion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030coneclassification.proto\022\022coneclassifi" +
      "cation\"9\n\010ConeInfo\022\014\n\004type\030\001 \001(\t\022\014\n\004size" +
      "\030\002 \001(\t\022\021\n\tcondition\030\003 \001(\t\" \n\nSuggestion\022" +
      "\022\n\nsuggestion\030\001 \001(\t2i\n\031ConeClassificatio" +
      "nService\022L\n\014ClassifyCone\022\034.coneclassific" +
      "ation.ConeInfo\032\036.coneclassification.Sugg" +
      "estionB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_coneclassification_ConeInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coneclassification_ConeInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coneclassification_ConeInfo_descriptor,
        new java.lang.String[] { "Type", "Size", "Condition", });
    internal_static_coneclassification_Suggestion_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_coneclassification_Suggestion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coneclassification_Suggestion_descriptor,
        new java.lang.String[] { "Suggestion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
