// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coneclassification.proto

package coneclassification;

/**
 * Protobuf type {@code coneclassification.Suggestion}
 */
public final class Suggestion extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coneclassification.Suggestion)
    SuggestionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Suggestion.newBuilder() to construct.
  private Suggestion(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Suggestion() {
    suggestion_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Suggestion();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Suggestion(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            suggestion_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return coneclassification.Coneclassification.internal_static_coneclassification_Suggestion_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return coneclassification.Coneclassification.internal_static_coneclassification_Suggestion_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            coneclassification.Suggestion.class, coneclassification.Suggestion.Builder.class);
  }

  public static final int SUGGESTION_FIELD_NUMBER = 1;
  private volatile java.lang.Object suggestion_;
  /**
   * <pre>
   * e.g., "Sell to Soltex", "Recycle", "Discard"
   * </pre>
   *
   * <code>string suggestion = 1;</code>
   * @return The suggestion.
   */
  @java.lang.Override
  public java.lang.String getSuggestion() {
    java.lang.Object ref = suggestion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      suggestion_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g., "Sell to Soltex", "Recycle", "Discard"
   * </pre>
   *
   * <code>string suggestion = 1;</code>
   * @return The bytes for suggestion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSuggestionBytes() {
    java.lang.Object ref = suggestion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      suggestion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(suggestion_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, suggestion_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(suggestion_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, suggestion_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof coneclassification.Suggestion)) {
      return super.equals(obj);
    }
    coneclassification.Suggestion other = (coneclassification.Suggestion) obj;

    if (!getSuggestion()
        .equals(other.getSuggestion())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUGGESTION_FIELD_NUMBER;
    hash = (53 * hash) + getSuggestion().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static coneclassification.Suggestion parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static coneclassification.Suggestion parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static coneclassification.Suggestion parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static coneclassification.Suggestion parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static coneclassification.Suggestion parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static coneclassification.Suggestion parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static coneclassification.Suggestion parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static coneclassification.Suggestion parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static coneclassification.Suggestion parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static coneclassification.Suggestion parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static coneclassification.Suggestion parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static coneclassification.Suggestion parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(coneclassification.Suggestion prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code coneclassification.Suggestion}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coneclassification.Suggestion)
      coneclassification.SuggestionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coneclassification.Coneclassification.internal_static_coneclassification_Suggestion_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coneclassification.Coneclassification.internal_static_coneclassification_Suggestion_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coneclassification.Suggestion.class, coneclassification.Suggestion.Builder.class);
    }

    // Construct using coneclassification.Suggestion.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      suggestion_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return coneclassification.Coneclassification.internal_static_coneclassification_Suggestion_descriptor;
    }

    @java.lang.Override
    public coneclassification.Suggestion getDefaultInstanceForType() {
      return coneclassification.Suggestion.getDefaultInstance();
    }

    @java.lang.Override
    public coneclassification.Suggestion build() {
      coneclassification.Suggestion result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public coneclassification.Suggestion buildPartial() {
      coneclassification.Suggestion result = new coneclassification.Suggestion(this);
      result.suggestion_ = suggestion_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof coneclassification.Suggestion) {
        return mergeFrom((coneclassification.Suggestion)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(coneclassification.Suggestion other) {
      if (other == coneclassification.Suggestion.getDefaultInstance()) return this;
      if (!other.getSuggestion().isEmpty()) {
        suggestion_ = other.suggestion_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      coneclassification.Suggestion parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (coneclassification.Suggestion) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object suggestion_ = "";
    /**
     * <pre>
     * e.g., "Sell to Soltex", "Recycle", "Discard"
     * </pre>
     *
     * <code>string suggestion = 1;</code>
     * @return The suggestion.
     */
    public java.lang.String getSuggestion() {
      java.lang.Object ref = suggestion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        suggestion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g., "Sell to Soltex", "Recycle", "Discard"
     * </pre>
     *
     * <code>string suggestion = 1;</code>
     * @return The bytes for suggestion.
     */
    public com.google.protobuf.ByteString
        getSuggestionBytes() {
      java.lang.Object ref = suggestion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        suggestion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g., "Sell to Soltex", "Recycle", "Discard"
     * </pre>
     *
     * <code>string suggestion = 1;</code>
     * @param value The suggestion to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      suggestion_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "Sell to Soltex", "Recycle", "Discard"
     * </pre>
     *
     * <code>string suggestion = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuggestion() {
      
      suggestion_ = getDefaultInstance().getSuggestion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "Sell to Soltex", "Recycle", "Discard"
     * </pre>
     *
     * <code>string suggestion = 1;</code>
     * @param value The bytes for suggestion to set.
     * @return This builder for chaining.
     */
    public Builder setSuggestionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      suggestion_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coneclassification.Suggestion)
  }

  // @@protoc_insertion_point(class_scope:coneclassification.Suggestion)
  private static final coneclassification.Suggestion DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new coneclassification.Suggestion();
  }

  public static coneclassification.Suggestion getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Suggestion>
      PARSER = new com.google.protobuf.AbstractParser<Suggestion>() {
    @java.lang.Override
    public Suggestion parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Suggestion(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Suggestion> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Suggestion> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public coneclassification.Suggestion getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

