// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coneclassification.proto

package coneclassification;

public interface SuggestionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coneclassification.Suggestion)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g., "Sell to Soltex", "Recycle", "Discard"
   * </pre>
   *
   * <code>string suggestion = 1;</code>
   * @return The suggestion.
   */
  java.lang.String getSuggestion();
  /**
   * <pre>
   * e.g., "Sell to Soltex", "Recycle", "Discard"
   * </pre>
   *
   * <code>string suggestion = 1;</code>
   * @return The bytes for suggestion.
   */
  com.google.protobuf.ByteString
      getSuggestionBytes();
}
